server:
  port: 8081

spring:
  application:
    name: auth-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8850 # Nacos 地址
        username: nacos        # 添加用户名
        password: nacos        # 添加密码
        namespace: cloud-ll      # 可选，命名空间
        group: DEFAULT_GROUP   # 可选，分组
      # Spring Boot 3.x 加载 Nacos 配置的必要设置（取代了旧版本的 bootstrap.yml）
      # 如果不使用 Nacos Config，可以写空
    config:
      import: 'optional:nacos:'  # 禁用配置中心强制检查